server:
  port: 8082

spring:
  profiles:
    active: dev

  application:
    name: userService

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

jwt:
  secret: ${MY_SECRET_KEY}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka